menu:
  mainmenu:
  - identifier: external--631280213-1627422093646
    name: external link
    url: http://example.com
    weight: 0
  - identifier: external--631280213-1627478990761
    name: new link
    url: http://example.com
    weight: 10
  - identifier: 417df552-369d-421a-b683-9683040e6de3
    name: other pdf link
    parent: external--631280213-1627422093646
    url: content/other-pdf.md
    weight: 0
